export const elements = {
  noteForm: document.getElementById('note-form'),
  noteIdInput: document.getElementById('note-id'),
  noteTitleInput: document.getElementById('note-title'),
  noteCategorySelect: document.getElementById('note-category'),
  noteContentInput: document.getElementById('note-content'),
  notePinnedCheckbox: document.getElementById('note-pinned'),
  submitBtn: document.getElementById('submit-btn'),
  cancelEditBtn: document.getElementById('cancel-edit-btn'),
  formTitle: document.getElementById('form-title'),
  charCounter: document.getElementById('char-counter'),
  searchInput: document.getElementById('search-input'),
  clearSearchBtn: document.getElementById('clear-search'),
  themeToggleBtn: document.getElementById('theme-toggle'),
  categoryFiltersContainer: document.getElementById('category-filters-container'),
  viewGridBtn: document.getElementById('view-grid'),
  viewListBtn: document.getElementById('view-list'),
  pinnedSectionWrapper: document.getElementById('pinned-section-wrapper'),
  pinnedNotesGrid: document.getElementById('pinned-notes-grid'),
  allNotesGrid: document.getElementById('all-notes-grid'),
  allNotesHeading: document.getElementById('all-notes-heading'),
  notesLoader: document.getElementById('notes-loader'),
  emptyStateContainer: document.getElementById('empty-state'),
  emptyStateText: document.getElementById('empty-state-text'),
  toastContainer: document.getElementById('toast-container')
};
